[Thu Feb 13 16:09:51 2014] [error] [client 127.0.0.1] File does not exist: /home/stx/public_html/http/favicon.ico
[Thu Feb 13 16:10:01 2014] [error] [client 127.0.0.1] File does not exist: /home/stx/public_html/http/flasktext1
[Thu Feb 13 16:16:44 2014] [error] [client 127.0.0.1] File does not exist: /home/stx/public_html/http/webapp
[Thu Feb 13 16:16:46 2014] [error] [client 127.0.0.1] File does not exist: /home/stx/public_html/http/webapp
[Thu Feb 13 16:16:49 2014] [error] [client 127.0.0.1] File does not exist: /home/stx/public_html/http/webapp
[Thu Feb 13 16:16:50 2014] [error] [client 127.0.0.1] File does not exist: /home/stx/public_html/http/webapp
[Thu Feb 13 16:16:51 2014] [error] [client 127.0.0.1] File does not exist: /home/stx/public_html/http/webapp
[Thu Feb 13 16:27:50 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12595): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 13 16:27:50 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12595): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 13 16:27:50 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 13 16:27:50 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 13 16:27:50 2014] [error] [client 127.0.0.1]     from webapp import app as application
[Thu Feb 13 16:27:50 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 4
[Thu Feb 13 16:27:50 2014] [error] [client 127.0.0.1] SyntaxError: Non-ASCII character '\\xc3' in file /home/stx/public_html/apps/webapp/webapp.py on line 4, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu Feb 13 16:27:57 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12597): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 13 16:27:57 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12597): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 13 16:27:57 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 13 16:27:57 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 13 16:27:57 2014] [error] [client 127.0.0.1]     from webapp import app as application
[Thu Feb 13 16:27:57 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 4
[Thu Feb 13 16:27:57 2014] [error] [client 127.0.0.1] SyntaxError: Non-ASCII character '\\xc3' in file /home/stx/public_html/apps/webapp/webapp.py on line 4, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu Feb 13 16:28:45 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12625): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 13 16:28:45 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12625): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 13 16:28:45 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 13 16:28:45 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 13 16:28:45 2014] [error] [client 127.0.0.1]     from webapp import webapp as application
[Thu Feb 13 16:28:45 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 4
[Thu Feb 13 16:28:45 2014] [error] [client 127.0.0.1] SyntaxError: Non-ASCII character '\\xc3' in file /home/stx/public_html/apps/webapp/webapp.py on line 4, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu Feb 13 16:28:46 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12624): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 13 16:28:46 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12624): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 13 16:28:46 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 13 16:28:46 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 13 16:28:46 2014] [error] [client 127.0.0.1]     from webapp import webapp as application
[Thu Feb 13 16:28:46 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 4
[Thu Feb 13 16:28:46 2014] [error] [client 127.0.0.1] SyntaxError: Non-ASCII character '\\xc3' in file /home/stx/public_html/apps/webapp/webapp.py on line 4, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu Feb 13 16:28:47 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12622): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 13 16:28:47 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12622): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 13 16:28:47 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 13 16:28:47 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 13 16:28:47 2014] [error] [client 127.0.0.1]     from webapp import webapp as application
[Thu Feb 13 16:28:47 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 4
[Thu Feb 13 16:28:47 2014] [error] [client 127.0.0.1] SyntaxError: Non-ASCII character '\\xc3' in file /home/stx/public_html/apps/webapp/webapp.py on line 4, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu Feb 13 16:31:13 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12648): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 13 16:31:13 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12648): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 13 16:31:13 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 13 16:31:13 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 13 16:31:13 2014] [error] [client 127.0.0.1]     from webapp import webapp as application
[Thu Feb 13 16:31:13 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 5
[Thu Feb 13 16:31:13 2014] [error] [client 127.0.0.1] SyntaxError: Non-ASCII character '\\xc3' in file /home/stx/public_html/apps/webapp/webapp.py on line 5, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu Feb 13 16:31:14 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12646): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 13 16:31:14 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12646): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 13 16:31:14 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 13 16:31:14 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 13 16:31:14 2014] [error] [client 127.0.0.1]     from webapp import webapp as application
[Thu Feb 13 16:31:14 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 5
[Thu Feb 13 16:31:14 2014] [error] [client 127.0.0.1] SyntaxError: Non-ASCII character '\\xc3' in file /home/stx/public_html/apps/webapp/webapp.py on line 5, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu Feb 13 16:31:17 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12649): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 13 16:31:17 2014] [error] [client 127.0.0.1] mod_wsgi (pid=12649): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 13 16:31:17 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 13 16:31:17 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 13 16:31:17 2014] [error] [client 127.0.0.1]     from webapp import webapp as application
[Thu Feb 13 16:31:17 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 5
[Thu Feb 13 16:31:17 2014] [error] [client 127.0.0.1] SyntaxError: Non-ASCII character '\\xc3' in file /home/stx/public_html/apps/webapp/webapp.py on line 5, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[Thu Feb 20 15:21:48 2014] [error] [client 127.0.0.1] File does not exist: /home/stx/public_html/http/favicon.ico
[Thu Feb 20 15:26:09 2014] [error] [client 127.0.0.1] mod_wsgi (pid=2018): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 20 15:26:09 2014] [error] [client 127.0.0.1] mod_wsgi (pid=2018): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 20 15:26:09 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 20 15:26:09 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 20 15:26:09 2014] [error] [client 127.0.0.1]     from webapp import webapp as application
[Thu Feb 20 15:26:09 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 25
[Thu Feb 20 15:26:09 2014] [error] [client 127.0.0.1]     textes=["1","2","3"]
[Thu Feb 20 15:26:09 2014] [error] [client 127.0.0.1]    ^
[Thu Feb 20 15:26:09 2014] [error] [client 127.0.0.1] IndentationError: unexpected indent
[Thu Feb 20 15:27:23 2014] [error] [client 127.0.0.1] mod_wsgi (pid=2016): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 20 15:27:23 2014] [error] [client 127.0.0.1] mod_wsgi (pid=2016): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 20 15:27:23 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 20 15:27:23 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 20 15:27:23 2014] [error] [client 127.0.0.1]     from webapp import webapp as application
[Thu Feb 20 15:27:23 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 25
[Thu Feb 20 15:27:23 2014] [error] [client 127.0.0.1]     textes=["1","2","3"]
[Thu Feb 20 15:27:23 2014] [error] [client 127.0.0.1]    ^
[Thu Feb 20 15:27:23 2014] [error] [client 127.0.0.1] IndentationError: unexpected indent
[Thu Feb 20 15:27:25 2014] [error] [client 127.0.0.1] mod_wsgi (pid=2019): Target WSGI script '/home/stx/public_html/wsgi/webapp.wsgi' cannot be loaded as Python module.
[Thu Feb 20 15:27:25 2014] [error] [client 127.0.0.1] mod_wsgi (pid=2019): Exception occurred processing WSGI script '/home/stx/public_html/wsgi/webapp.wsgi'.
[Thu Feb 20 15:27:25 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Thu Feb 20 15:27:25 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/wsgi/webapp.wsgi", line 3, in <module>
[Thu Feb 20 15:27:25 2014] [error] [client 127.0.0.1]     from webapp import webapp as application
[Thu Feb 20 15:27:25 2014] [error] [client 127.0.0.1]   File "/home/stx/public_html/apps/webapp/webapp.py", line 25
[Thu Feb 20 15:27:25 2014] [error] [client 127.0.0.1]     textes=["1","2","3"]
[Thu Feb 20 15:27:25 2014] [error] [client 127.0.0.1]    ^
[Thu Feb 20 15:27:25 2014] [error] [client 127.0.0.1] IndentationError: unexpected indent
[Thu Feb 20 15:32:28 2014] [error] [client 127.0.0.1] File does not exist: /home/stx/public_html/http/favicon.ico
